---
# tasks file for k8s-master By Mohamed Ayman <M.Ayman2612@gmail.com>

- name: add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Load Configuration for a specific OS
  include: "{{ ansible_os_family }}.yml"
